name: CI

on:
  push:
    paths:
      - '**.py'
      - '.github/**'
  pull_request:

jobs:
  test-and-fuzz:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m venv .venv
          . .venv/bin/activate
          pip install --upgrade pip
          pip install bandit networkx

      - name: Run Bandit hook
        run: |
          . .venv/bin/activate
          # scan the entire repo (or change to $FILES logic if you prefer)
          bandit -r . -f csv -o bandit_report.csv
          if [ -s bandit_report.csv ]; then
            echo "❌ Bandit found issues! See bandit_report.csv"
            cat bandit_report.csv
            exit 1
          fi

      - name: Compute fuzz targets
        run: |
          . .venv/bin/activate
          python graph_analysis.py

      - name: Run fuzzer
        run: |
          . .venv/bin/activate
          python fuzz.py

      - name: Upload fuzz report
        uses: actions/upload-artifact@v4
        with:
          name: fuzz-csv
          path: fuzz.csv
